# clash 配置文件

# 混合端口
mixed-port: 7890

# 允许局域网连接
allow-lan: true

# 绑定地址
bind-address: '*'

# 运行模式
mode: rule

# 日志级别
log-level: info

# IPv6 支持
ipv6: false

# DNS 配置
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '+.lan'
    - '+.local'
    - 'localhost.ptlogin2.qq.com'
  nameserver:
    - 223.6.6.6
    - 223.5.5.5
    - 119.29.29.29
    - 10.1.1.1
    - 10.1.1.2
    - 10.1.1.3
  fallback:
    - https://1.1.1.1/dns-query
    - https://8.8.8.8/dns-query

# 机场订阅
proxy-providers:
  AP1:
    type: http
    url: "" # 修改为你的机场订阅地址
    interval: 86400
    path: ./profiles/proxies/AP1.yaml
    health-check:
      enable: true
      interval: 300
      url: http://www.gstatic.com/generate_204

# 代理组
proxy-groups:
  - name: Proxy
    type: select
    use:
      - AP1

  - name: AI
    type: select
    use:
      - AP1

# 规则集
rule-providers:

  openai:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/OpenAI/OpenAI.yaml"
    path: ./ruleset/openai.yaml
    interval: 86400
  direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400
  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400
  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400

# 规则
rules:
  # AI
  - RULE-SET,openai,AI

  # 国内网站
  - RULE-SET,direct,DIRECT

  # IP规则
  - RULE-SET,lancidr,DIRECT,no-resolve
  - RULE-SET,cncidr,DIRECT,no-resolve

  # 最终规则
  - GEOIP,CN,DIRECT
  - MATCH,Proxy
